#!/bin/sh
# Script to package the website up

t=site.$(git log --oneline -n 1 --abbrev=10 --format=format:%h HEAD)
mkdir "$t"

( cd code ; ./scriptmin -c ./clipscript t.xhtml ) > "$t"/index.xhtml

mkdir "$t"/doc
cp -pr doc/what "$t"/doc/
cp -pr gallery "$t"/
# gzip "$t"/doc/*/*
# gzip "$t"/gallery/*.xhtml
ls -laR "$t"
echo "$t"
