#!/bin/sh
# $Id: //depot/prj/logoscript/master/package#11 $
# Script to package the website up

t="site.$$"
mkdir "$t"

( cd code ; ./scriptmin -c ./jsmin1 t.xhtml ) | gzip -c > "$t"/index.xhtml.gz

mkdir "$t"/doc
cp -pr doc/what "$t"/doc/
cp -pr gallery "$t"/
gzip "$t"/doc/*/*
gzip "$t"/gallery/*.xhtml
ls -laR "$t"
echo "$t"
